### PR TITLE
update for diffView

### PR DESCRIPTION
**Pull request by harshitks2203**

### CODE REVIEW

**Comment by Jay9596** [comment]
Why did add the counter variable ? It is never used anywhere.

**Comment by harshitks2203** [comment]
yeah... I was testing for the mistake and at last, I forgot to delete that. I will take care of such mistakes from next time

**Comment by apollonian11** [comment]
Should this be merged? I forgot to keep track of this..

**Comment by apollonian11** [comment]
@harshitks2203 please make a PR to the `develop` branch https://github.com/Jay9596/CodePad/pull/2/commits/ef48ba27e0e1febfb1559db31d104f21f1c7a37a only would be fine

**Comment by apollonian11** [comment]
@harshitks2203 I haven't pushed the diff view update to master. have a separate branch on your repo for it.

**Pull request merged**
